spring:
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      keyspace-name: spring_cassandra
      entity-base-package: com.perficient.infrastructure.adapter.out.persistence.entity

grpc:
  server:
    port: 6565